# ─── RedShadow V1 Configuration File ───
# Developed by Galal Noaman – RedShadow_V1
# For educational and lawful use only.
# Customize timeouts, ports, recon options, CVE analysis, and reporting.

domain:
  timeout: 20                # HTTP request timeout (seconds)
  retries: 3                 # Retry attempts for HTTP or header fetch failures
  delay: 2                   # Delay between retry attempts (seconds)
  headers:
    User-Agent: "RedShadowBot/1.0 (+https://github.com/GalalNoaman/RedShadow_V1)"

scan:
  nmap_ports: "21-25,53,80,443,8080,8443"   # Common external ports
  max_threads: 12                           # Max threads for DNS and Nmap parallel scans
  dns_servers:                              # Primary + fallback resolvers
    - "8.8.8.8"
    - "1.1.1.1"
    - "9.9.9.9"
    - "208.67.222.222"
   # - "185.228.168.9"
   # - "94.140.14.14" 
   # - "45.90.28.0"  

passive:
  verify_ssl: false             # Don't block scans on cert errors (bug bounty-friendly)
  delay: 0.5                    # Faster recon (can increase for stealth)

analyse:
  cve_source: "data/cve_map.json"   # Path to CVE map (auto-loaded by analyse.py)

report:
  include_cvss: true
  include_links: true
  theme: "light"

defaults:
  output_dir: "outputs"
  debug: false                  # Enable debug logging (planned)
